# Generated by Django 4.0 on 2021-12-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('contact_number', models.IntegerField()),
                ('student_address', models.CharField(max_length=80)),
            ],
        ),
    ]
